Lesson1 develop
Buguinya/65appsHomeProject pull request #1
Opened 2019-09-20 15:31 UTC by Buguinya

No proper configuration change handling, receiving email and image

2019-09-20 16:34 UTC, Buguinya commented
lesson1 вместо мастер пока

2019-09-20 18:14 UTC, goblinr requested changes

2019-09-20 18:14 UTC, goblinr commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_7" project-jdk-name="1.8" project-jdk-type="JavaSDK">
папку .idea в .gitignore

2019-09-20 18:14 UTC, goblinr commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
папку .idea в .gitignore

2019-09-20 18:14 UTC, goblinr commented on app/src/main/AndroidManifest.xml
>          android:allowBackup="true"
`android:allowBackup` желательно запрещать по умолчанию

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/appManagers/ContactsManager.kt
> +        private lateinit var _instance : ContactsManager
`_instance ` - этот стиль для приватных полей не принят в Kotlin или Java

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/appManagers/ContactsManager.kt
> +        fun getInstance() : ContactsManager{
пробел после `ContactsManager`

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/appManagers/ContactsManager.kt
> +                _instance = ContactsManager()
В Kotlin для синглетонов есть `object`

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/appManagers/ContactsManager.kt
> +        val isPermissionDenied = (ContextCompat.checkSelfPermission(activity, Manifest.permission.CAMERA) == PackageManager.PERMISSION_DENIED)
Зачем мы проверяем разрешение на камеру, когда нам нужно разрешение на чтение контактов? И метод называется `requestCameraPermission`, когда должен называться `requestContactsPermission`

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/appManagers/PageManager.kt
> +    fun onCameraAccessGranted()
Здесь то же название колбэка про камеру а не про контакты

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/appManagers/ContactsManager.kt
> +        private lateinit var _instance : ContactsManager
Это касается всего остального кода так же. Нужно поправить везде.

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/appManagers/PageManager.kt
> +        Snackbar.make(_activity!!.fragmentsContainer, message, Snackbar.LENGTH_LONG).show()
`!!` - не должно быть в коде

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/appManagers/PageManager.kt
> +        Snackbar.make(_activity!!.fragmentsContainer, message, Snackbar.LENGTH_LONG).show()
Это касается всех остальных мест, нужно исправить везде

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/common/Utils.kt
> +            view = View(activity)
Так делать не нужно. Stack Overflow(откуда это было взято, судя по всему) нужно применять осторожно.

Это не будет работать с фрагментами

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/appManagers/PageManager.kt
> +         _fragmentManager = activity.supportFragmentManager
Здесь происходит утечка памяти. `_fragmentManager ` нигде не обнуляется, соответственно GC не сможет освободить память занятую под `AppCompatActivity` т.к. активность связана с `FragmentManager`  жесткой ссылкой. 
Более того `onCreate` у `PageManager` вызывается только при первоначальном создании активности, соответственно, после смены конфигурации, мы гарантированно получим утечку памяти и ссылка на  `FragmentManager` будет указывать на `FragmentManager` уничтоженной активности

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/fragm_con_detailed/DetailedContract.kt
> +package com.zhuravlevmikhail.a65appshomeproject.core.fragm_con_detailed
`fragm_con_detailed` -  `_` в названии пакета - так делать не стоит

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/fragm_con_detailed/DetailedContract.kt
> +    interface TModel : MvpModel
`TModel` - так не принято называть классы/интерфейсы в Kotlin или Java

Это касается всех остальных мест в коде. Нужно поправить везде

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/fragm_con_detailed/DetailedContract.kt
> +        ): Observable<Bitmap>*/
Закомменченный код следует удалить

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/fragm_con_detailed/DetailedPresenter.kt
> +        BasePresenter<DetailedView, DetailedModel>(model){
пробел перед `{`

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/fragm_con_detailed/DetailedContract.kt
> +        fun queryContactWithoutImageAsync(contentResolver: ContentResolver, contactId: Long): Observable<DetailedModel.ContactDetailed>
Вместо `Observable` здесь больше подходит `Single`

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/fragm_con_detailed/DetailedPresenter.kt
> +    override fun queryContactWithoutImageAsync(contentResolver: ContentResolver, contactId: Long): Observable<DetailedModel.ContactDetailed> =
`Observable` -> `Single`

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/fragm_con_detailed/DetailedPresenter.kt
> +        Observable.create { emitter: ObservableEmitter<DetailedModel.ContactDetailed> ->
`Observable.create` -> `Single.fromCallable`

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/fragm_con_detailed/DetailedPresenter.kt
> + /*   override fun queryContactImageAsync(contentResolver: ContentResolver, contactId: Long) : Observable<Bitmap> =
Закомменченный код следует удалить

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/fragm_con_detailed/DetailedPresenter.kt
> +            contactsCursor.close()
Курсор следует закрывать в `finally` блоке. 

Это относится ко всем остальным местам. Нужно поправить везде

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/fragm_con_detailed/DetailedPresenter.kt
> +  /*  private fun getContactImage(contentResolver: ContentResolver, contactId : Long) : Bitmap? {
Закомменченный код удалить

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/fragm_con_detailed/DetailedView.kt
> +        _disposable = _mvpPresenter.queryContactWithoutImageAsync(activity!!.contentResolver, _contactId)
Не вижу что бы перед запросом контактов, спрашивалось разрешение на чтение контактов - это гарантированный крэш

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/fragm_con_detailed/DetailedView.kt
> +       /* _disposableImage = _mvpPresenter.queryContactImageAsync(activity!!.contentResolver, _contactId)
Закомменченный код

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/fragm_contact/ContactHolder.kt
> +            _clickListener.onClick(itemView, model.id)
Назначать `OnClickListener` следует в конструкторе `ViewHolder` и только там.

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/fragm_contact/ContactsContract.kt
> +        ): Observable<ArrayList<ContactsModel.ContactGeneral>>
`Observable` -> `Single`

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/fragm_contact/ContactsContract.kt
> +        fun onCameraAccessGranted()
Почему камера?

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/fragm_contact/ContactsView.kt
> +        _disposable = _mvpPresenter.queryContactsAsync(activity!!.contentResolver)
Опять не спрашиваем разрешение перед чтением контактов

2019-09-20 18:14 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/mvpAchitecture/BaseFragmAndView.kt
> +    private var _fragmentData: HashMap<String, Any>? = null
Для передачи данных в фрагмент существует специальный механизм - аргументы. И следует использовать именно его.

2019-09-22 13:19 UTC, goblinr requested changes

2019-09-22 13:19 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/contacts/ContactHolder.kt
> +            clickListener.onClick(itemView, adapterPosition)
`adapterPosition` нужно проверять на `NO_POSITION` перед использованием

2019-09-22 20:53 UTC, goblinr requested changes

2019-09-22 20:53 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/AppHostActivity.kt
> +        pageManager.setContactsPage()
Ты уверен, что нужно ра каждый `onResume` открывать экран списка контактов? Я думаю - это будет не дружелюбно по отношению к пользователю приложения. Т.е. при каждом сворачивании - разворачивании приложеня - пользователя будет перекидывать на главный экран.

2019-09-23 05:47 UTC, goblinr requested changes

2019-09-23 05:47 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/appManagers/PageManager.kt
> +        fragmentManager = activity.supportFragmentManager
Лишние пробелы перед `lifecyclesForApp `

2019-09-23 05:53 UTC, goblinr requested changes

2019-09-23 05:53 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/mvpAchitecture/BaseFragmAndView.kt
> +    protected lateinit var _mvpPresenter: Presenter
Название поля не соответствует стандартам кодирования на Kotlin

2019-09-23 06:05 UTC, goblinr requested changes

2019-09-23 06:05 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/contacts/ContactsView.kt
> +            disposable = mvpPresenter.queryContactsAsync(it!!.contentResolver)
`!!` - не должно быть в коде

2019-09-23 06:06 UTC, goblinr requested changes

2019-09-23 06:06 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/contacts/ContactsView.kt
> +        if (!ContactsManager.requestContactsPermission(activity!!)) {
`!!`

2019-09-23 06:20 UTC, goblinr commented
Наблюдается такой баг:
При первоначальном запуске приложения, появляется диалог запроса на чтение контактов.
После того как разрешение дано - список контактов не подтягивается, пользователь видит пустой экран
При повторном заходе в приложение - список контактов уже подтягивается

2019-09-23 06:48 UTC, Buguinya commented
> Наблюдается такой баг:
> При первоначальном запуске приложения, появляется диалог запроса на чтение контактов.
> После того как разрешение дано - список контактов не подтягивается, пользователь видит пустой экран
> При повторном заходе в приложение - список контактов уже подтягивается

Проблема в том, что в момент получения onRequestPermissionResult fragmentManager является null, так как нулится в onPause, а вызов onResult происходит позже. 
Я предполагаю, что fragmentManager можно перенести в onDestroy

2019-09-23 06:53 UTC, goblinr commented
> Проблема в том, что в момент получения onRequestPermissionResult fragmentManager является null, так как нулится в onPause, а вызов onResult происходит позже.
Я предполагаю, что fragmentManager можно перенести в onDestroy

Нет, тогда будет возможность выполнить транзакцию фрагмента после `onPause`
Правильно будет воспользоваться паттерном проектирования - "Команда". Пока fragmentManager == null, все запросы на транзакцию фрагментов помещаются в очередь команд. Когда fragmentManager проинициализирован - запускается выполнение очереди команд накопившихся за время пока fragmentManager == null

2019-09-23 07:00 UTC, goblinr requested changes

2019-09-23 07:00 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/appManagers/PageManager.kt
> +        fragmentManager = activity.supportFragmentManager
`fragmentManager` нужно инициализировать в `onResumeFragments`  методе жизненного цикла `AppCompatActivity`

2019-09-26 08:13 UTC, goblinr approved these changes

2019-09-26 08:14 UTC, merged