Lesson1 cicerone navigation
Buguinya/65appsHomeProject pull request #2
Opened 2019-09-25 15:00 UTC by Buguinya

Пока не убираю pageManager (на нем завязан базовый mvpView, его я потом заменю на Moxy)

2019-09-25 15:27 UTC, goblinr requested changes

2019-09-25 15:27 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/AppHostActivity.kt
> +                App.instance.cicerone.router.newRootScreen(ContactsScreen())
Зачем мы здесь посылаем `NewRootScreen` команду? Разве мы этого уже не сделали в `onCreate`? Получается, что после получения разрешения пользователя - мы принудительно отправляем его на главный экран, где бы он на данный момент не находился, даже если он итак находится на главном экране.

Я понимаю, что без этого у тебя не загрузятся контакты и не обновится список на экране, но решать эту проблему нужно не таким способом. По-нормальному, разрешение на чтение контактов должен спрашивать сам фрагмент главного экрана и он самже должен обрабатывать ответ пользователя, этим не должна заниматься активность.

2019-09-25 15:53 UTC, Buguinya commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/AppHostActivity.kt
> +                App.instance.cicerone.router.newRootScreen(ContactsScreen())
Понятно, но что если перед onRequestPermissionResult фрагмент успеет уйти в onPause?

2019-09-25 16:40 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/AppHostActivity.kt
> +                App.instance.cicerone.router.newRootScreen(ContactsScreen())
Что значит "успеет"? Он в любом случае, перед onRequestPermissionResult в paused состоянии находится, т.к. системный диалог, который показывается пользователю для запроса разрешения - модальный, все приложение в paused состояние переводится на время показа этого диалога.

Поэтом, разрешение нельзя спрашивать в onResume - будет бесконечный запрос разрешения, если пользователь будет всякий раз нажимать "Нет"

2019-09-26 05:13 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/AppHostActivity.kt
> +    private val navigator = SupportAppNavigator(this, R.id.fragmentsContainer)
Property следует указывать в начале класса, в соответствии со стандартами кодирования на Kotlin

2019-09-26 07:52 UTC, goblinr approved these changes

2019-09-26 08:05 UTC, merged