Lesson2 mvp moxy
Buguinya/65appsHomeProject pull request #4
Opened 2019-09-27 10:47 UTC by Buguinya

2019-09-30 05:50 UTC, goblinr requested changes

2019-09-30 05:50 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/core/AppHostActivity.kt
> -        App.instance.cicerone.navigatorHolder.removeNavigator()
Зачем удалил `removeNavigator` из `onPause`? Это гарантированный крэш приложения, если транзакция фрагмента произойдет после `onPause`

2019-09-30 05:50 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/fragments/contacts/ContactsFragment.kt
> +        this.onContactsAccessGranted()
Инициатором проверки и запроса разрешений должен быть презентер. Ведь именно он загружает данные из модели. Т.е. алгоритм действий должен быть такой:

- В onFirstViewAttach презентер посылает команду View на проверку разрешений.
- Презентер ждет сигнала от View что можно загружать контакты, View тем временем занимается проверкой разрешения и запросом разрешения у пользователя, если разрешение еще не было дано
- При получении сигнала от View, презентер подписывается на загрузку контактов из модели
- При получении списка контактов презентер посылает команду View отобразить список
- View отображает список контактов через адаптер RecyclerView

2019-09-30 05:50 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/fragments/detail/DetailedFragment.kt
> +        detailedPresenter.queryContactAsync(contactId)
Инициатором загрузки данных контакта должен быть презентер.
Он должен в onFirstViewAttach начать загрузку данных без ведома View.
При этом он должен предварительно узнать у View - есть ли разрешение на чтение контактов. Все так же как и со списком контактов.

2019-09-30 16:54 UTC, Buguinya commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/fragments/contacts/ContactsFragment.kt
> +        this.onContactsAccessGranted()
А обработка permisson result'a это же тоже логика, разве этим view должно заниматься?

2019-09-30 16:58 UTC, Buguinya commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/fragments/contacts/ContactsFragment.kt
> +        this.onContactsAccessGranted()
Или настолько мелкую логику можно во view оставлять?

2019-10-01 04:39 UTC, goblinr requested changes

2019-10-01 04:39 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/fragments/contacts/ContactsView.kt
> +    fun askContactsPermisson()
`AddToEndSingleStrategy` - не подходит для всех команд представленных в этом списке.
`askContactsPermisson` - нужно выполнить только 1 раз, его не нужно сново выполнять после пересоздания View
`openDetailedContactPage` - так же не нужно выполнять вновь после пересоздания View - это приведет к тому что после каждого поворота экрана будет открываться новый фрагмент деталей контакта

Нужно разобраться со стратегиями для каждой команды

2019-10-01 04:39 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/fragments/contacts/ContactsFragment.kt
> +       if (!PermissionManager.requestContactsPermission(this)) {
Зачем это делать здесь? В `onContactsAccessGranted` это уже проверяется 
и название метода `onContactsAccessGranted` - сбивает с толку

2019-10-01 04:39 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/fragments/detail/DetailedView.kt
> +    fun requestContactsPermisson()
Здесь так же нужно разобраться со стратегиями

2019-10-01 06:18 UTC, goblinr requested changes

2019-10-01 06:18 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/fragments/contacts/ContactsView.kt
> +    fun checkContactsAccess()
`AddToEndSingleStrategy` не нужен для `checkContactsAccess` т.к. мы не хотим проверять разрешения и загружать контакты при каждом новом `onViewAttach` презентера. Мы хотим сделать это 1 раз при старте презентера, и далее во View будут передаваться уже загруженные данные при ее пересоздании.

2019-10-01 06:18 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/fragments/detail/DetailedView.kt
> +    fun requestContactsPermission()
Здесь так же, `AddToEndSingleStrategy` не подходит для этой команды.

2019-10-02 04:49 UTC, goblinr requested changes
На данный момент наблюдаю такой баг:

- Созданы 2 тестовых аккаунта с заданными телефонами и email
- Заходим в приложение, дожидаемся подгрузки списка контактов
- Переходим в детали одного из контактов

В итоге - контакт пуст и показывается тост о том что email не должен быть пустым, хотя email у контакта был задан при создании.

2019-10-02 11:17 UTC, Buguinya commented
> На данный момент наблюдаю такой баг:
> 
> * Созданы 2 тестовых аккаунта с заданными телефонами и email
> * Заходим в приложение, дожидаемся подгрузки списка контактов
> * Переходим в детали одного из контактов
> 
> В итоге - контакт пуст и показывается тост о том что email не должен быть пустым, хотя email у контакта был задан при создании.

Добавил отдельный запрос на email, теперь работает

2019-10-03 04:29 UTC, goblinr approved these changes

2019-10-03 04:29 UTC, merged