Added progress indication
Buguinya/65appsHomeProject pull request #8
Opened 2019-10-11 12:49 UTC by Buguinya

2019-10-13 10:24 UTC, goblinr requested changes

2019-10-13 10:24 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/fragments/contacts/ContactsPresenter.kt
> +                .doOnSubscribe { viewState.showProgress(true)}
`viewState.showProgress(true)` устанавливается, но не вижу, где снимается флаг.

Так же просмотрел на прошлом задании. Сейчас есть баг:
если пользователь не дал разрешение на чтение контактов и начинает вводить текст в строку поиска - получаем гарантированную ошибку. Нужно спрашивать пользователя разрешение на чтение контактов перед каждой попыткой чтения контактов.

2019-10-14 09:58 UTC, Buguinya commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/fragments/contacts/ContactsPresenter.kt
> +                .doOnSubscribe { viewState.showProgress(true)}
Наверное я неправильно понял, но вроде флаг снимается в Single.onSuccess и onError

2019-10-17 07:44 UTC, goblinr requested changes

2019-10-17 07:44 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/fragments/contacts/ContactsFragment.kt
> +                isVisible = isPermissionGranted
Это не решение проблемы.
Вот такой алгоритм должен быть - https://github.com/alex-izh/65appsUniver/pull/3#discussion_r335848935

2019-10-17 08:50 UTC, Buguinya commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/fragments/contacts/ContactsFragment.kt
> +                isVisible = isPermissionGranted
Репозиторий приватный, судя по всему

2019-10-21 04:56 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/fragments/contacts/ContactsFragment.kt
> +                isVisible = isPermissionGranted
В случае если пользователь не дал разрешение в прошлый раз - у него вновь необходимо запросить разрешение, а не игнорировать ввод пользователя. Пользователь ожидает, что на его действия в приложении - будет понятная реакция.

Алгоритм такой:
- перед чтением контактов проверяем наличие разрешения
- если разрешения нет - запрашиваем его у пользователя, если разрешение есть - начинаем загрузку контактов
- если пользователь не дал разрешения, сообщаем пользователю, что функция не доступна без разрешения
- если пользователь не дал разрешение и нажал галочку, не спрашивать в следующий раз(в этом случае при запросе разрешения в следующий раз - сразу вернется результат с отрицательным значением) -  сообщаем пользователю, что функция не доступна без разрешения и нужно зайти в настройки приложения и вручную включить разрешение на чтение контактов
- если пользователь дал разрешение - начинаем загрузку контактов

2019-10-22 05:20 UTC, goblinr requested changes

2019-10-22 05:20 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/fragments/contacts/ContactsPresenter.kt
> +            .add(contactsRepository.getAllQueredContacts(name)
Теперь необходимо избавиться от множества устаревших подписок. Когда пользователь вводит текст, каждый раз создается новая подписка, старая подписка становится уже не актуальной и следует отписаться от нее.

2019-10-23 04:18 UTC, goblinr requested changes

2019-10-23 04:18 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/fragments/contacts/ContactsPresenter.kt
> +        compositeDisposable.dispose()
Это опасно. Если в `compositeDisposable` будут в будущем подписки, относящиеся к другим операциям - это приведет к тому, что операция поиска контактов будет отменять все эти подписки.

2019-10-23 05:41 UTC, svos10 requested changes

2019-10-23 05:41 UTC, svos10 commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/fragments/contacts/ContactsFragment.kt
> +            if (grantResults[0] == PackageManager.PERMISSION_GRANTED) {
Можно избавиться от вложенных if, если все условия написать через  &&

2019-10-23 06:41 UTC, svos10 commented
Баг: если при вводе имени (во время поиска контакта) меняем ориентацию телефона, то режим поиска прекращается и может быть ситуация, что экран со списком контактов оказывается пустым.

2019-10-23 12:42 UTC, goblinr requested changes

2019-10-23 12:42 UTC, goblinr commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/fragments/contacts/ContactsPresenter.kt
> +    private var queryContactDisposables = CompositeDisposable()
`CompositeDisposable` здесь уже лишнее.
```kotlin
private var queryContactDisposable = Disposables.disposed
```
далее в `queryContactsByName`:
```kotlin
queryContactDisposable.dispose()
queryContactDisposable = contactsRepository.getAllQueriedContacts(name)
/*CODE*/
. subscribe(/*CODE*/)
```

2019-10-24 04:44 UTC, goblinr approved these changes

2019-10-24 04:54 UTC, svos10 commented on app/src/main/java/com/zhuravlevmikhail/a65appshomeproject/fragments/contacts/ContactsFragment.kt
> +            if (grantResults[0] == PackageManager.PERMISSION_GRANTED) {
Вложенный if так и не был удален

2019-10-24 11:01 UTC, merged